name: learn-github-actions
run-name: Automated Testing CI/CD
on: [push]
jobs:
  check-rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7.6']

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Setup chrome driver (for Selenium)
        uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Check RSpec
        env:
          RAILS_ENV: 'test'
          DB_HOST: 'localhost'
          DB_NAME: 'ci_d_test'
          DB_USERNAME: 'postgres'
          DB_PASSWORD: 'postgres'
        run : |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rspec
      - name: Cucumber Report to Annotations
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.json"
